### ISSUE TITLE
Npm.depends() is usually outside of Package.onUse()

### ISSUE THREAD

**Issue by mikowals** [Dev1an/meteor-fibers-bug#1]
It is not specified in docs but [a quick search](https://github.com/meteor/meteor/search?utf8=%E2%9C%93&q=Npm.depends) of the meteor repository shows putting Npm.depends() inside the `.onUse()` call is not standard.

**Comment by Dev1an** [comment]
I moved `Npm.depends()` outside the `Package.onUse` function. But running meteor still gives me the same error.
